### ISSUE TITLE
3차팀장 배영훈3

### ISSUE THREAD

**Issue by cksgh8538** [2021-SMHRD-KDT-AI-4/Null-in#3]
- [ ]3차팀장 배영훈
- [x] 3차팀장 배영훈
- [x] 3차팀장 배영훈
- [x] 3차팀장 배영훈
- [x] 3차팀장 배영훈
- [x] 3차팀장 배영훈
- [ ]

**Comment by YeongHunBae** [comment]
그만~~!

**Comment by cksgh8538** [comment]
- [ ]
